const CLIENT_PACKET = {
  game: {
    CreateRoomRequest: 512,
    CreateRoomResponse: 513,
    JoinRoomRequest: 514,
    JoinRoomResponse: 515,
  },
  account: {
    RegistAccountRequest: 500,
    RegistAccountResponse: 501,
    LoginRequest: 502,
    LoginResponse: 503,
    ChangeNicknameRequest: 504,
    ChangeNicknameResponse: 505,
  },
  lobby: {
    EnterLobbyRequest: 506,
    EnterLobbyResponse: 507,
    RefreshLobbyRequest: 508,
    RefreshLobbyResponse: 509,
    SearchRoomRequest: 510,
    SearchRoomResponse: 511,
  },
  dedicated: {
    PlayerMoveRequest: 1,
    PlayerMoveNotification: 2,
    GhostMoveRequest: 3,
    GhostMoveNotification: 4,
    PingRequest: 5, // S2C
    PingResponse: 6, // C2S
    PlayerStateChangeRequest: 7,
    PlayerStateChangeNotification: 8,
    GhostStateChangeRequest: 9,
    GhostStateChangeNotification: 10,
    ItemChangeRequest: 11,
    ItemChangeNotification: 12,
    StartStageRequest: 23,
    SpawnInitialDataRequest: 24,
    SpawnInitialDataResponse: 25,
    StartStageNotification: 26,
    PlayerAttackedRequest: 27,
    PlayerLifeResponse: 28,
    GhostAttackedRequest: 29,
    ItemGetRequest: 30,
    ItemGetResponse: 31,
    ItemUseRequest: 32,
    ItemUseResponse: 33,
    ItemUseNotification: 34,
    ItemDiscardRequest: 35,
    ItemDiscardResponse: 36,
    ItemDiscardNotification: 37,
    DoorToggleRequest: 38,
    DoorToggleNotification: 39,
    StageEndNotification: 40,
    ExtractSoulRequest: 41,
    ExtractSoulNotification: 42,
    DisconnectPlayerNotification: 43,
    GhostSpecialStateRequest: 44,
    GhostSpecialStateNotification: 45,
    ItemDeleteNotification: 46,
    ItemDisuseRequest: 47,
    ItemDisuseNotification: 48,
    ItemCreateRequest: 49,
    ItemCreateNotification: 50,
    BlockInteractionNotification: 51,
    GhostSpawnRequest: 52,
    GhostSpawnNotification: 53,
    ItemGetNotification: 54,
    RemainingTimeNotification: 55,
    ItemPurchaseRequest: 56,
    ItemPurchaseNotification: 57,
    ItemPurchaseResponse: 58,
    JoinRoomResponse: 515,
    JoinRoomNotification: 516,
  },
};

export default CLIENT_PACKET;
