export const packetNames = {
  common: {
    GamePacket: 'common.GamePacket',
    ServicePacket: 'common.ServicePacket',
  },
};

export const PACKET_TYPE = {
  game: {
    PlayerMoveRequest: 1,
    PlayerMoveNotification: 2,
    GhostMoveRequest: 3,
    GhostMoveNotification: 4,
    PingRequest: 5, // S2C
    PingResponse: 6, // C2S
    PlayerStateChangeRequest: 7,
    PlayerStateChangeNotification: 8,
    GhostStateChangeRequest: 9,
    GhostStateChangeNotification: 10,
    ItemChangeRequest: 11,
    ItemChangeNotification: 12,
    StartStageRequest: 23,
    SpawnInitialDataRequest: 24,
    SpawnInitialDataResponse: 25,
    StartStageNotification: 26,
    PlayerAttackedRequest: 27,
    PlayerLifeResponse: 28,
    GhostAttackedRequest: 29,
    ItemGetRequest: 30,
    ItemGetResponse: 31,
    ItemUseRequest: 32,
    ItemUseResponse: 33,
    ItemUseNotification: 34,
    ItemDiscardRequest: 35,
    ItemDiscardResponse: 36,
    ItemDiscardNotification: 37,
    DoorToggleRequest: 38,
    DoorToggleNotification: 39,
    StageEndNotification: 40,
    ExtractSoulRequest: 41,
    ExtractSoulNotification: 42,
    DisconnectPlayerNotification: 43,
    GhostSpecialStateRequest: 44,
    GhostSpecialStateNotification: 45,
    ItemDeleteNotification: 46,
    ItemDisuseRequest: 47,
    ItemDisuseNotification: 48,
    ItemCreateRequest: 49,
    ItemCreateNotification: 50,
    BlockInteractionNotification: 51,
    GhostSpawnRequest: 52,
    GhostSpawnNotification: 53,
    ItemGetNotification: 54,
    RemainingTimeNotification: 55,
    ItemPurchaseRequest: 56,
    ItemPurchaseNotification: 57,
    ItemPurchaseResponse: 58,
    JoinRoomResponse: 515,
    JoinRoomNotification: 516,
  },
  service: {
    ConnectServiceRequest: 1,
    ConnectedServiceNotification: 2,
    DisconnectServiceRequest: 3,
    DisconnectedServiceNotification: 4,
    CreateDedicatedRequest: 5,
    ExitDedicatedRequest: 6,
    ConnectDedicateRequest: 7,
    JoinDedicatedRequest: 8,
  },
};

export const PACKET_MAPS = {
  client: {
    [PACKET_TYPE.game.PlayerMoveRequest]: 'playerMoveRequest',
    [PACKET_TYPE.game.PlayerMoveNotification]: 'playerMoveNotification',
    [PACKET_TYPE.game.GhostMoveRequest]: 'ghostMoveRequest',
    [PACKET_TYPE.game.GhostMoveNotification]: 'ghostMoveNotification',
    [PACKET_TYPE.game.PingRequest]: 'pingRequest', // S2C
    [PACKET_TYPE.game.PingResponse]: 'pingResponse', // C2S
    [PACKET_TYPE.game.PlayerStateChangeRequest]: 'playerStateChangeRequest',
    [PACKET_TYPE.game.PlayerStateChangeNotification]:
      'playerStateChangeNotification',
    [PACKET_TYPE.game.GhostStateChangeRequest]: 'ghostStateChangeRequest',
    [PACKET_TYPE.game.GhostStateChangeNotification]:
      'ghostStateChangeNotification',
    [PACKET_TYPE.game.ItemChangeRequest]: 'itemChangeRequest',
    [PACKET_TYPE.game.ItemChangeNotification]: 'itemChangeNotification',
    [PACKET_TYPE.game.StartStageRequest]: 'startStageRequest',
    [PACKET_TYPE.game.SpawnInitialDataRequest]: 'spawnInitialDataRequest',
    [PACKET_TYPE.game.SpawnInitialDataResponse]: 'spawnInitialDataResponse',
    [PACKET_TYPE.game.StartStageNotification]: 'startStageNotification',
    [PACKET_TYPE.game.PlayerAttackedRequest]: 'playerAttackedRequest',
    [PACKET_TYPE.game.PlayerLifeResponse]: 'playerLifeResponse',
    [PACKET_TYPE.game.GhostAttackedRequest]: 'ghostAttackedRequest',
    [PACKET_TYPE.game.ItemGetRequest]: 'itemGetRequest',
    [PACKET_TYPE.game.ItemGetResponse]: 'itemGetResponse',
    [PACKET_TYPE.game.ItemUseRequest]: 'itemUseRequest',
    [PACKET_TYPE.game.ItemUseResponse]: 'itemUseResponse',
    [PACKET_TYPE.game.ItemUseNotification]: 'itemUseNotification',
    [PACKET_TYPE.game.ItemDiscardRequest]: 'itemDiscardRequest',
    [PACKET_TYPE.game.ItemDiscardResponse]: 'itemDiscardResponse',
    [PACKET_TYPE.game.ItemDiscardNotification]: 'itemDiscardNotification',
    [PACKET_TYPE.game.DoorToggleRequest]: 'doorToggleRequest',
    [PACKET_TYPE.game.DoorToggleNotification]: 'doorToggleNotification',
    [PACKET_TYPE.game.StageEndNotification]: 'stageEndNotification',
    [PACKET_TYPE.game.ExtractSoulRequest]: 'extractSoulRequest',
    [PACKET_TYPE.game.ExtractSoulNotification]: 'extractSoulNotification',
    [PACKET_TYPE.game.DisconnectPlayerNotification]:
      'disconnectPlayerNotification',
    [PACKET_TYPE.game.ItemDeleteNotification]: 'itemDeleteNotification',
    [PACKET_TYPE.game.ItemDisuseRequest]: 'itemDisuseRequest',
    [PACKET_TYPE.game.ItemDisuseNotification]: 'itemDisuseNotification',
    [PACKET_TYPE.game.ItemCreateRequest]: 'itemCreateRequest',
    [PACKET_TYPE.game.ItemCreateNotification]: 'itemCreateNotification',
    [PACKET_TYPE.game.BlockInteractionNotification]:
      'blockInteractionNotification',
    [PACKET_TYPE.game.GhostSpawnRequest]: 'ghostSpawnRequest',
    [PACKET_TYPE.game.GhostSpawnNotification]: 'ghostSpawnNotification',
    [PACKET_TYPE.game.ItemGetNotification]: 'itemGetNotification',
    [PACKET_TYPE.game.RemainingTimeNotification]: 'remainingTimeNotification',
    [PACKET_TYPE.game.ItemPurchaseRequest]: 'itemPurchaseRequest',
    [PACKET_TYPE.game.ItemPurchaseNotification]: 'itemPurchaseNotification',
    [PACKET_TYPE.game.ItemPurchaseResponse]: 'itemPurchaseResponse',
    [PACKET_TYPE.game.JoinRoomResponse]: 'joinRoomResponse',
    [PACKET_TYPE.game.JoinRoomNotification]: 'joinRoomNotification',
  },
  service: {
    [PACKET_TYPE.service.ConnectServiceRequest]: 'connectServiceRequest',
    [PACKET_TYPE.service.ConnectedServiceNotification]:
      'connectedServiceNotification',
    [PACKET_TYPE.service.DisconnectServiceRequest]: 'disconnectServiceRequest',
    [PACKET_TYPE.service.DisconnectedServiceNotification]:
      'disconnectedServiceNotification',
    [PACKET_TYPE.service.CreateDedicatedRequest]: 'createDedicatedRequest',
    [PACKET_TYPE.service.ExitDedicatedRequest]: 'exitDedicatedRequest',
    [PACKET_TYPE.service.ConnectDedicateRequest]: 'connectDedicateRequest',
    [PACKET_TYPE.service.JoinDedicatedRequest]: 'joinDedicatedRequest',
  },
};
