# Node.js LTS 이미지 사용
FROM node:18

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# 루트 package.json 및 yarn.lock 복사
COPY ../../../package.json ../../../yarn.lock ./

# Dedicated 전용 package.json 복사
COPY ./package.json ./

# 의존성 설치
RUN yarn install --frozen-lockfile

# Dedicated 디렉토리의 파일 복사
COPY . .

# 런타임 환경 설정
ENV NODE_ENV=production

# 서버 실행 포트 노출
EXPOSE 3000

# Dedicated 서버 실행
CMD ["node", "src/dedicate.server.js"]
