name: Simple Deploy to EC2

on:
  push:
    branches: ['dev'] # 또는 원하는 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/Peekaboo_TestServer
            git pull origin dev # 최신 코드 가져오기

            # 도커 빌드 캐시 삭제
            docker builder prune -f
            # docker system prune -af

            # Docker Compose 재시작
            docker-compose down || true  # 에러 무시
            yarn docker-compose:build

            # 컨테이너 상태 확인
            docker ps
